version: 0.2

env:
  variables:
    PROJECT: AspWithNUnit
    DOTNET_FRAMEWORK: 4.5
phases:
    #install:
        #runtime-versions:
            #DOTNET_FRAMEWORK: 4.5
        #commands:
          #- dotnet tool install -g AWS.CodeArtifact.NuGet.CredentialProvider
          #- dotnet codeartifact-creds install
          #- //"SDGAPP-113,SDGAPP-114 (SDGAPP-136, SDGAPP-135, SDGAPP-134, SDGAPP-133 = inside story)= epic ,
          #- //SDGAPP-119,SDGAPP-120 = story ,
          #- //SDGAPP-121,SDGAPP-122,SDGAPP-137 = bug"
          #- SDGAPP-113/c,SDGAPP-119/c,SDGAPP-112/o_Addition,Multiplication,Registration  01  02  03
          #- SDGAPP-1/c_Addition,Multiplication,Registration 01 02 03 04 05 06 07 08 09 10 11 12  13
          #- SDGAPP-1/c_Addition,Multiplication,Registration 01  02 03 04 05 06 07 08 09
          #- SDGAPP-1/c_All 01 02 03 04 05 06 07 08 09 10
          
          
    build:
        commands:
           - nuget restore
           #- apt-get update && apt-get install -y lcov
           #- genhtml
           - msbuild AspWithNUnit.sln /p:TargetFrameworkVersion=v4.5 /p:Configuration=Release /p:DeployIisAppPath="Default Web Site" /p:PackageAsSingleFile=false /p:OutDir=C:\codebuild\artifacts\ /t:Package
artifacts:
  files:
    - '**/*'
  base-directory: 'C:\codebuild\artifacts\_PublishedWebsites\${env:PROJECT}_Package\Archive\'


